### ISSUE TITLE
[Bug]: It shows an error that the mod sound controller 1.0.1 requires version 0.14.24 or later of fabricloader but only the wrong version if present 0.14.22

### ISSUE THREAD

**Issue by FastPhase** [BVengo/sound-controller#8]
### Describe the Bug

at first i thught i had the wrong fabric version installed but the latest version of fabric is only 0.11.2 way far that 0.14.22
i searched a lot but cannot come up with a fix

### Steps to Reproduce

I am on tlauncher and it has fabric installed. The error occures when i open the game with this mod 

### Expected Behavior

i expected it to be compatible with older fabric versions

### Screenshots

![image_2023-12-07_121139345](https://github.com/BVengo/sound-controller/assets/145282583/e998b4f0-904a-4608-b8d9-ea87bde0d9a2)

### Fabric Version

0.14.22

### Mod Version

1.0.1

**Comment by BVengo** [comment]
Hi! Thanks for your bug report.

I believe what you're thinking of is the fabric _installer_, downloaded from the fabric website (which is only version 0.11.2). The installer helps configure a new instance for your mods, and lets them run using any selected version of the fabric loader. The latest version of the loader is now 0.15.0!

If using the fabric installer to download mods, please select the latest loader version (now 0.15.0) when setting up your instance.
![image](https://github.com/BVengo/sound-controller/assets/43019560/8f94d7f5-01dd-4e56-a066-c18970a58181)

Any mods you currently have installed can be copied over to the new instance, and you shouldn't have any issues with newer mods like this one :)

Hope this helps!

**Comment by BVengo** [comment]
Just installed TLauncher so I could be a little more help.

If you're installing it as a custom modpack within TLauncher, change the fabric version of your modpack to be 0.15.0.
![image](https://github.com/BVengo/sound-controller/assets/43019560/31943ef6-fccd-4b48-901a-c9c3d60491dd)
